[build]
command = 'bun run build'
functions = 'functions'
publish = 'dist'

[dev]
port = 5000
targetPort = 4321

[[headers]]
for = '/*'
[headers.values]
Access-Control-Allow-Origin = '*'
Referrer-Policy = 'same-origin'
X-Content-Type-Options = 'nosniff'
X-Frame-Options = 'sameorigin'

[[headers]]
for = '/public/*'
[headers.values]
cache-control = '''
    max-age=31536000
    immutable
    '''

[[headers]]
for = '/manifest.webmanifest'
[headers.values]
Content-Type = 'application/manifest+json'
