[build]
command = 'bun run build'
functions = 'netlify/functions'
publish = 'dist'
[build.processing.html]
pretty_urls = true

[dev]
autoLaunch = true
command = 'bun dev'
framework = '#custom'
functionsPort = 5001
port = 5000
publish = 'dist'
targetPort = 4321
[dev.https]
certFile = 'cert.pem'
keyFile = 'key.pem'

[[headers]]
for = '/*'
[headers.values]
access-control-allow-origin = '*'
referrer-policy = 'same-origin'
x-content-type-options = 'nosniff'
x-frame-options = 'sameorigin'

[[headers]]
for = '/manifest.webmanifest'
[headers.values]
content-type = 'application/manifest+json'

[[redirects]]
from = '/*'
status = 200
to = '/'
