[build]
command = 'bun run build'
functions = 'netlify/functions'
publish = 'dist'

[dev]
autoLaunch = true
command = 'bun dev'
framework = '#custom'
functionsPort = 5001
port = 5000
publish = 'dist'
targetPort = 4321
[dev.https]
certFile = 'certs/cert.pem'
keyFile = 'certs/key.pem'

[[headers]]
for = '/*'
[headers.values]
access-control-allow-origin = 'https://k-astro.netlify.app'
content-security-policy = 'block-all-mixed-content'
permissions-policy = 'geolocation=(self), microphone=(self)'
referrer-policy = 'same-origin'
x-content-type-options = 'nosniff'
x-frame-options = 'sameorigin'
